version: "3.8"

services:
  dns:
    build: ./dns
    container_name: dns_projetoeng
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      projeto_net:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql_projetoeng
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: projetoeng
      MYSQL_USER: projeto
      MYSQL_PASSWORD: projetopass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      projeto_net:
        ipv4_address: 172.28.0.20
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_projetoeng
    ports:
      - "6379:6379"
    networks:
      projeto_net:
        ipv4_address: 172.28.0.21
    restart: unless-stopped

  web01:
    build: ./web
    container_name: web01_projetoeng
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=projeto
      - MYSQL_PASSWORD=projetopass
      - MYSQL_DATABASE=projetoeng
      - REDIS_HOST=redis
      - SESSION_SECRET=segredo_super
      - SESSION_COOKIE_DOMAIN=.projetoeng.com.br
    depends_on:
      - mysql
      - redis
    ports:
      - "3001:3000"
    networks:
      projeto_net:
        ipv4_address: 172.28.0.30
    restart: unless-stopped

  web02:
    build: ./web
    container_name: web02_projetoeng
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=projeto
      - MYSQL_PASSWORD=projetopass
      - MYSQL_DATABASE=projetoeng
      - REDIS_HOST=redis
      - SESSION_SECRET=segredo_super
      - SESSION_COOKIE_DOMAIN=.projetoeng.com.br
    depends_on:
      - mysql
      - redis
    ports:
      - "3002:3000"
    networks:
      projeto_net:
        ipv4_address: 172.28.0.31
    restart: unless-stopped

  web03:
    build: ./web
    container_name: web03_projetoeng
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=projeto
      - MYSQL_PASSWORD=projetopass
      - MYSQL_DATABASE=projetoeng
      - REDIS_HOST=redis
      - SESSION_SECRET=segredo_super
      - SESSION_COOKIE_DOMAIN=.projetoeng.com.br
    depends_on:
      - mysql
      - redis
    ports:
      - "3003:3000"
    networks:
      projeto_net:
        ipv4_address: 172.28.0.32
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_projetoeng
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web01
      - web02
      - web03
    networks:
      projeto_net:
        ipv4_address: 172.28.0.11
    restart: unless-stopped

networks:
  projeto_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16